In [223]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [224]:
a = np.arange(1,21)
b = 2*np.ones(20)
pow(b,a)/a

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [225]:
a = np.ones(5)
b = a*((0.1)**(3*(-1)**0.5)*(0.2)**(4*(-1)**0.5))
sum(b)

(3.557603425592456-3.5133257557779607j)

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [226]:
a = np.zeros((8,8), dtype=int)
a[::2,::2]=1
a[1::2,1::2]=1
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [227]:
X = np.random.random((5, 2))
Y = (X**2).transpose()
ro = np.sqrt(sum(Y))
phi = np.arctan2(X[:,1], X[:,0])
Z = np.array([ro,phi]).transpose()
Z

array([[1.03924175, 0.56098966],
       [0.70556116, 1.1669613 ],
       [1.19345893, 0.78259203],
       [0.96143512, 0.4707841 ],
       [0.26892491, 1.46486413]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [228]:
X = np.random.random((10, 10))
ind1 = np.argmax(X, axis=0)
ind2 = np.argmax(X, axis=1)
max(X[ind1,ind2])

0.9996796798474841

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [230]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
index = np.sqrt(((X-y)[:,0])**2+((X-y)[:,1])**2).argmin()
X[index]

array([0.53347902, 0.6523174 ])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [231]:
arr1 = np.linspace(-3,0,50)
arr2= np.linspace(0,2,50)
arr3 = np.linspace(2,3,50)
a = arr1**2+2*arr1+6
b = arr2+6
c = arr3**2+4*arr3-4
result = np.concatenate((a,b,c), axis=0)
result

array([ 9.        ,  8.75885048,  8.52519783,  8.29904207,  8.08038317,
        7.86922116,  7.66555602,  7.46938776,  7.28071637,  7.09954186,
        6.92586422,  6.75968347,  6.60099958,  6.44981258,  6.30612245,
        6.1699292 ,  6.04123282,  5.92003332,  5.8063307 ,  5.70012495,
        5.60141608,  5.51020408,  5.42648896,  5.35027072,  5.28154935,
        5.22032486,  5.16659725,  5.12036651,  5.08163265,  5.05039567,
        5.02665556,  5.01041233,  5.00166597,  5.00041649,  5.00666389,
        5.02040816,  5.04164931,  5.07038734,  5.10662224,  5.15035402,
        5.20158267,  5.2603082 ,  5.32653061,  5.4002499 ,  5.48146606,
        5.57017909,  5.666389  ,  5.77009579,  5.88129946,  6.        ,
        6.        ,  6.04081633,  6.08163265,  6.12244898,  6.16326531,
        6.20408163,  6.24489796,  6.28571429,  6.32653061,  6.36734694,
        6.40816327,  6.44897959,  6.48979592,  6.53061224,  6.57142857,
        6.6122449 ,  6.65306122,  6.69387755,  6.73469388,  6.77

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [232]:
X = np.random.random((10, 10))
average = (np.repeat([np.mean(X,axis=1)],10,axis=0)).transpose()
result = X - average
result

array([[ 0.17658245, -0.46237287, -0.21856356, -0.00459612, -0.25811735,
        -0.2547503 ,  0.20284977,  0.27780975,  0.24778783,  0.29337042],
       [-0.05106961, -0.4091551 , -0.12653337, -0.04516973, -0.10936604,
         0.30066313,  0.08775147,  0.13314324, -0.21547492,  0.43521093],
       [-0.03061265,  0.46468679,  0.1063448 , -0.27050287,  0.35829928,
        -0.27923777,  0.09053801, -0.34156587,  0.14699575, -0.24494547],
       [ 0.15513786,  0.05952041, -0.45726913, -0.35008227, -0.10438336,
         0.09575132,  0.36735476,  0.17742756, -0.35831962,  0.41486248],
       [ 0.12220363,  0.35044963,  0.26328156,  0.07761296, -0.1170018 ,
         0.35020842, -0.324682  , -0.23176048, -0.51287454,  0.02256261],
       [-0.02372933, -0.16937432,  0.28532071, -0.11830013, -0.03952181,
        -0.28978328, -0.04298336, -0.14991825,  0.4099647 ,  0.13832507],
       [ 0.00912807,  0.26596648,  0.26277225,  0.39721908, -0.43721829,
        -0.04410013, -0.06152544, -0.46449071

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [233]:
X = np.random.normal(loc=5, scale=2., size=1000)
average = np.sum(X)/len(X)
disp = np.sum(X**2)/len(X)-average**2
print(average,disp)

5.156554270510141 4.3370145626188155


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [234]:
arr =  np.arange(0,5)
result = np.concatenate(([arr],[np.roll(arr, -1)],[np.roll(arr, -2)],[np.roll(arr, -3)],[np.roll(arr, -4)]))
result

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [235]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [236]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []    
    X = np.repeat([x],c,axis=0)
    idx = np.ones(c,dtype=int)
    Idx = np.repeat([idx],c,axis=0)
    rand = np.random.random(c)
    val = s*rand
    Val = np.repeat([val],c,axis=0).transpose()
    res = Idx.sum(where = np.cumsum(X, axis=1)<=Val, axis=1)
    return res

sample([50, 3, 1, 7, 20], 5)    

array([0, 0, 0, 0, 4])